name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build Docker Images
      # WAR for cosmo in github workflow
      run: |
        sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"
        make all

    - name: Push Docker Images
      run: make push

